### PR TITLE
IOS-933 Updating Release Log For 4.0.4

### PR DESCRIPTION
**Pull request by GregFrankVungle**
Updating release notes for the new SDK 4.0.4 release

### CODE REVIEW

**Comment by GregFrankVungle** [comment]
David's Changes look good to me

**Comment by DavidKimVungle** [comment]
Greg's changes on release note looks good to me!

**Comment by DavidKimVungle** [comment]
Greg's change on .podspec looks good.

**Comment by GregFrankVungle** [comment]
Approved by David for my changes and I approved David's Changes.

**Pull request merged**
